### ISSUE TITLE
[High Priority] Running with issue while configuring Power BI Direct Query to Azure Cosmos DB Via Spark Cluster on HDInside

### ISSUE THREAD

**Issue by shrutikamendhe** [Azure/azure-cosmosdb-spark#128]
I am following guidelines provided [here](https://github.com/Azure/azure-cosmosdb-spark/wiki/Configuring-Power-BI-Direct-Query-to-Azure-Cosmos-DB-via-Apache-Spark-(HDI)) to configure Power BI Direct Query. 

As specified in the instruction, I have copied the **azure-cosmosdb-spark_2.1.0_2.11-0.0.4.jar** file from https://github.com/Azure/azure-cosmosdb-spark/tree/master/releases/azure-cosmosdb-spark_2.1.0_2.11-0.0.4 folder in all the nodes running in the cluster. After restarting Spark services, I unable to run the further instruction as specified in the article. 

I also observed that I could not run the notebook which was running before setting the configuration.

![jupyter-error](https://user-images.githubusercontent.com/9589742/30438945-26bbe5d4-9990-11e7-94bd-f50790306a01.png)

Please let me know if I missed anything.

**Comment by dennyglee** [comment]
Hi @shrutikamendhe - please note that for the second part concerning the notebook, you will need to restart the kernel for Jupyter notebook.  As well, it will be a good idea to have separate clusters between regular notebook traffic and Power BI traffic until we provide a script action that will allow you to more easily copy the jars to the right folder.

On the first part, could you please
* Refresh your key since the screenshot contains your master key
* Please note, could you copy all of the JARs in the folder except the uber JAR or copy just the uber-jar.  

I've re-emphasized this point in the original instructions.  HTH!

**Comment by shrutikamendhe** [comment]
Thanks, @dennyglee. I will try out the solution and let us know the results.

**Comment by shrutikamendhe** [comment]
Hello, @dennyglee - I could configure the Power BI direct query to Cosmos DB via Spark HDI. While researching, I found this email trail https://www.mail-archive.com/user@spark.apache.org/msg63521.html and found that instead of downloading jars via blob, should download it using raw URL and it worked like a miracle :smile:!!!

Thanks again for all your support.

**Comment by dennyglee** [comment]
Glad it worked!  :)
