### ISSUE TITLE
Sample of azure-documentdb-spark

### ISSUE THREAD

**Issue by PerthCharern** [Azure/azure-cosmosdb-spark#22]
I don't think the example provided in azure-documentdb-spark works. spark.sqlContext cannot be resolved (and even if it can be, should the example use SparkSession given that sqlContext has been deprecated?)

I'm still confused on how to use this to read and write to DocumentDB. Here's what I'm doing:

```
val documentDBSpark = DocumentDBSpark.load(sparkSession, readConfig2)
documentDBSpark.rdd.saveAsTextFile("DocumentDB/" + System.currentTimeMillis())
```

Interestingly, I'm getting the right number of documents (3 in my Doc DB) back but the content is empty. 

```
[]
[]
[]
```

I don't think I'm using the right command. Could anyone please help advise?

Thank you.

**Comment by dennyglee** [comment]
Hi @perthcha - to clarify, are you referring to the [Spark-to-DocumentDB_Sample.scala](https://github.com/Azure/azure-documentdb-spark/blob/14c959500dc996674f36438001ff1520ed6a54d5/samples/scripts/Spark-to-DocumentDB_Sample.scala) script?  

Per that script:
```
// Create collection connection 
val coll = spark.sqlContext.read.DocumentDB(readConfig2)
coll.createOrReplaceTempView("c")
```
We are specifying the sqlContext as part of the Spark Session - and the reason for this is because the `.read.DocumentDB` portion of it is part of `azure-documentdb-spark` instead of the the Spark Session code-base; hence why the explicit call out.

The script [DocumentDBRDDSpec.scala](https://github.com/Azure/azure-documentdb-spark/blob/14c959500dc996674f36438001ff1520ed6a54d5/src/test/scala/com/microsoft/azure/documentdb/spark/DocumentDBRDDSpec.scala) have examples for loading and saving, perhaps they could be of help?  Meanwhile, we are working to document more examples as per #13

**Comment by perthcha** [comment]
Yup, that code.

If I use that code with the library, my IntelliJ is complaining that `read` cannot be resolved. I also cannot locate in the source where `read.DocumentDB` is extended for SQLContext type. Could you help point to that code? Or, is there any other library I also need to install?

**Comment by khdang** [comment]
@perthcha, ```SQLContext.read``` is actually part of Spark and not DocumentDB specific. Can you check the dependencies again? The ```DocumentDB``` is extended as part of [
DataFrameReaderFunctions.scala](https://github.com/Azure/azure-documentdb-spark/blob/master/src/main/scala/com/microsoft/azure/documentdb/spark/schema/DataFrameReaderFunctions.scala)

**Comment by perthcha** [comment]
Thanks for your help! I was missing this dependency: http://mvnrepository.com/artifact/org.apache.spark/spark-sql_2.11

I'll close this.

**Comment by perthcha** [comment]
Thanks you both. I managed to get this to work.

@dennyglee : What I meant was that SqlContext does not need to be called explicitly in spark anymore. (in version 2.0). Here is how I think the code should look like:

```
// Create collection connection 
val coll = spark.read.DocumentDB(readConfig2)
coll.createOrReplaceTempView("c")
```
 
where spark is of type `SparkSession`. 

I'm using the pattern similar to above and I can see the data being from DocumentDB fine.

**Comment by dennyglee** [comment]
Oh that's fair, we were just being explicit about it. Up for creating a PR, would be glad to merge it, eh?!
