### ISSUE TITLE
Getting "cosmosdb_connector_shaded.io.reactivex.netty.client.PoolExhaustedException" Exception

### ISSUE THREAD

**Issue by kanagapinnacle** [Azure/azure-cosmosdb-spark#235]
I am using structure Streaming of data from Kafka to CosmosDB. when I increase the "WritingBatchSize" value I am getting "PoolExhausedException". Only when I set "ConnectionMaxPoolSize" same as "writingBatchSize" I am not getting this exception. 
1. Is it the correct configuration to use?
2. Any other parameter we need to adjust?

**Comment by nomiero** [comment]
For the right configurations to have for structured stream write:
Yes, for structured streaming, you would want the pool size to be >= writing batch size but not too big to the point of starting to have connection timeouts because there are no resources in the machine to fit the connection pool size 

For batch write with bulk import ( the default for batch write ) you want your pool size to be at least >= number of partitions in Cosmos Db and also not too big to the point of starting to have connection timeouts because there are no resources in the machine to fit the connection pool size
