### ISSUE TITLE
Azure Cosmos DB with Databricks Upsert

### ISSUE THREAD

**Issue by shrey-agarwal** [Azure/azure-cosmosdb-spark#337]
I have a cosmosDB account on Azure. I have inserted 10 rows with primary key "unique_ID" via databricks using spark connector "azure-cosmosdb-spark_2.4.0_2.11-1.3.4-uber.jar"

The cosmosDB container is set with unique_ID as unique key.
Multiple issues:

To upsert next set of records with same unique_IDs but different field values, I am unable to do so successfully. The query I am using:
connectionConfig = {
"Endpoint" : "https://.documents.azure.com:443/",
"Masterkey" : "",
"Database" : "",
"preferredRegions" : "East US",
"Collection": "",
"Upsert" : "true"
}

data.write.format("com.microsoft.azure.cosmosdb.spark").options(**connectionConfig).save()

This fails!
Error: Writing-to-a-non-empty-table.

So, I use the next query:

data.write.format("com.microsoft.azure.cosmosdb.spark").mode("append").options(**connectionConfig).save()

This fails too!
Error: Unique index constraint violation.

Replacing mode "append" to "overwrite" gives exactly the same error message.

How do I go about updating my records ?

What I dont understand is, shouldn't overwrite at least work and overwrite the whole database with new records?

Any help would be appreciated.

Thanks!

**Comment by nomiero** [comment]
overwrite means replace documents for the connector. 
In your case, documents are not being replaced because you have a unique constraint on a property and you are probably passing an id and partition key that are different from the one that already exists in the collection 
For example if you have 3 properties in your doc id, pk, uniqueProp with values a,b,c and then you try to insert d,b,c it will fail because it's a totally different document and it's violating the unique constraint of the collection.
If you need to replace the document, you need to have the same id and partition key because these properties are the ones that unique identify the document.
You can find more details on partitioning here
https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview

If you need to delete the collection and recreate it, you will need to use either cosmos python sdk or java sdk in your spark job to delete the collection.

**Comment by yasar-kaya** [comment]
But id is system generated, how can we force the source document to have the same id as the target document during the update process. ?
